/**
 * Open Grunker — a QR encoder, small enough to keep.
 *
 * There is exactly one thing in this game that needs a QR code: the
 * `otpauth://` URI an authenticator app scans when somebody turns on two-factor
 * authentication. Asking a player to retype a 32-character base32 secret into a
 * phone is how a security feature ends up switched off, and pulling in a
 * library — or worse, a chart API on somebody else's server — to draw one
 * rectangle would put a third party between this account and its own secret.
 *
 * So: byte mode, error-correction level M, versions 1 to 10, which is far more
 * than the ~120 characters an otpauth URI ever runs to. Everything below is
 * ISO/IEC 18004 by the letter — the arithmetic is not open to interpretation.
 */

/* ── Galois field GF(256) ─────────────────────────────────────────────────
   Reed-Solomon runs over the field generated by x^8 + x^4 + x^3 + x^2 + 1
   (0x11d). Two lookup tables turn multiplication into an addition of logs. */

const EXP = new Uint8Array(512);
const LOG = new Uint8Array(256);
(() => {
  let x = 1;
  for (let i = 0; i < 255; i++) {
    EXP[i] = x;
    LOG[x] = i;
    x <<= 1;
    if (x & 0x100) x ^= 0x11d;
  }
  for (let i = 255; i < 512; i++) EXP[i] = EXP[i - 255];
})();

const mul = (a, b) => (a === 0 || b === 0 ? 0 : EXP[LOG[a] + LOG[b]]);

/**
 * The generator polynomial for `degree` error-correction codewords:
 * the product of (x - a^i) for i in [0, degree).
 *
 * Coefficients run highest power first, so `poly[0]` is always 1 — which is
 * what the synthetic division in `rsEncode` relies on when it reads `gen[i+1]`.
 * Multiplying by one more (x + a^i) is therefore two terms: `poly * x`, which
 * keeps each coefficient's index in an array one longer, and `poly * a^i`,
 * which moves each one down a power.
 */
function rsGenerator(degree) {
  let poly = [1];
  for (let i = 0; i < degree; i++) {
    const next = new Array(poly.length + 1).fill(0);
    for (let j = 0; j < poly.length; j++) {
      next[j] ^= poly[j];                       // × x
      next[j + 1] ^= mul(poly[j], EXP[i]);      // × a^i
    }
    poly = next;
  }
  return poly;
}

/** The `degree` error-correction codewords for one data block. */
function rsEncode(data, degree) {
  const gen = rsGenerator(degree);
  const rem = new Uint8Array(degree);
  for (const byte of data) {
    const factor = byte ^ rem[0];
    rem.copyWithin(0, 1);
    rem[degree - 1] = 0;
    for (let i = 0; i < degree; i++) rem[i] ^= mul(gen[i + 1], factor);
  }
  return rem;
}

/* ── Version tables (level M only) ────────────────────────────────────────
   Per version 1-10: total codewords, EC codewords per block, and the block
   split. Straight out of the standard's tables 7 and 9. */

const VERSIONS = [
  // [totalCodewords, ecPerBlock, group1Blocks, group2Blocks]
  null,
  [26, 10, 1, 0],     // v1
  [44, 16, 1, 0],     // v2
  [70, 26, 1, 0],     // v3
  [100, 18, 2, 0],    // v4
  [134, 24, 2, 0],    // v5
  [172, 16, 4, 0],    // v6
  [196, 18, 4, 0],    // v7
  [242, 22, 2, 2],    // v8
  [292, 22, 3, 2],    // v9
  [346, 26, 4, 1],    // v10
];

/** Where the alignment patterns go, per version. */
const ALIGN = [
  null, [], [6, 18], [6, 22], [6, 26], [6, 30], [6, 34],
  [6, 22, 38], [6, 24, 42], [6, 26, 46], [6, 28, 50],
];

const sizeFor = (version) => version * 4 + 17;

/** Data codewords a version holds at level M, and how the blocks divide. */
function capacityOf(version) {
  const [total, ecPer, g1, g2] = VERSIONS[version];
  const blocks = g1 + g2;
  const dataTotal = total - ecPer * blocks;
  // Group 2's blocks each carry exactly one more codeword than group 1's.
  const short = Math.floor(dataTotal / blocks);
  return { total, ecPer, g1, g2, blocks, dataTotal, short };
}

/* ── Format & version information ─────────────────────────────────────── */

/** 15-bit format string: EC level M (0b00) plus the mask, BCH-protected. */
function formatBits(mask) {
  const data = (0b00 << 3) | mask;
  let rem = data;
  for (let i = 0; i < 10; i++) rem = (rem << 1) ^ ((rem >>> 9) * 0x537);
  return ((data << 10) | rem) ^ 0x5412;
}

/** 18-bit version string, on version 7 and up only. */
function versionBits(version) {
  let rem = version;
  for (let i = 0; i < 12; i++) rem = (rem << 1) ^ ((rem >>> 11) * 0x1f25);
  return (version << 12) | rem;
}

/* ── The matrix ───────────────────────────────────────────────────────── */

/**
 * Lays down everything that is not data: finders, separators, timing,
 * alignment, the dark module and the reserved format/version areas.
 *
 * @returns {{modules: Int8Array, reserved: Uint8Array}} `modules` is -1 where
 *   nothing has been placed yet, so the data pass can tell empty from black.
 */
function skeleton(version) {
  const n = sizeFor(version);
  const modules = new Int8Array(n * n).fill(-1);
  const reserved = new Uint8Array(n * n);
  const at = (r, c) => r * n + c;
  const set = (r, c, v) => {
    if (r < 0 || c < 0 || r >= n || c >= n) return;
    modules[at(r, c)] = v ? 1 : 0;
    reserved[at(r, c)] = 1;
  };

  // Three finder patterns, each with its separator.
  for (const [top, left] of [[0, 0], [0, n - 7], [n - 7, 0]]) {
    for (let r = -1; r <= 7; r++) {
      for (let c = -1; c <= 7; c++) {
        const inner = r >= 0 && r <= 6 && c >= 0 && c <= 6;
        const ring = inner && (r === 0 || r === 6 || c === 0 || c === 6
          || (r >= 2 && r <= 4 && c >= 2 && c <= 4));
        set(top + r, left + c, ring);
      }
    }
  }

  // Timing patterns along row 6 and column 6.
  for (let i = 8; i < n - 8; i++) {
    set(6, i, i % 2 === 0);
    set(i, 6, i % 2 === 0);
  }

  // Alignment patterns, skipping the three that would sit on a finder.
  const centres = ALIGN[version];
  for (const r of centres) {
    for (const c of centres) {
      if ((r === 6 && c === 6) || (r === 6 && c === n - 7) || (r === n - 7 && c === 6)) continue;
      for (let dr = -2; dr <= 2; dr++) {
        for (let dc = -2; dc <= 2; dc++) {
          set(r + dr, c + dc, Math.max(Math.abs(dr), Math.abs(dc)) !== 1);
        }
      }
    }
  }

  // The areas the format string will occupy, then the always-dark module.
  //
  // Index 6 is skipped in both directions on purpose: (8,6) and (6,8) are
  // timing modules, not format modules. Writing over them here would break the
  // timing pattern the scanner uses to find the grid at all.
  for (let i = 0; i < 9; i++) {
    if (i !== 6) { set(8, i, false); set(i, 8, false); }
  }
  for (let i = 0; i < 8; i++) { set(8, n - 1 - i, false); set(n - 1 - i, 8, false); }
  set(n - 8, 8, true);
  if (version >= 7) {
    for (let i = 0; i < 18; i++) {
      set(Math.floor(i / 3), n - 11 + (i % 3), false);
      set(n - 11 + (i % 3), Math.floor(i / 3), false);
    }
  }
  return { modules, reserved };
}

/**
 * Writes the finished format string into both of its copies.
 *
 * The layout is not symmetric and the two copies do not run the same way round:
 * the first climbs column 8 and then runs left along row 8, the second runs
 * along row 8 from the right edge and then climbs column 8 from the bottom.
 * Both are written low bit first.
 */
function placeFormat(modules, n, mask) {
  const bits = formatBits(mask);
  const put = (r, c, i) => { modules[r * n + c] = ((bits >>> i) & 1) === 1 ? 1 : 0; };

  // Copy one, around the top-left finder.
  for (let i = 0; i <= 5; i++) put(i, 8, i);
  put(7, 8, 6);
  put(8, 8, 7);
  put(8, 7, 8);
  for (let i = 9; i < 15; i++) put(8, 14 - i, i);

  // Copy two: along the top-right, then up from the bottom-left.
  for (let i = 0; i <= 7; i++) put(8, n - 1 - i, i);
  for (let i = 8; i < 15; i++) put(n - 15 + i, 8, i);
  modules[(n - 8) * n + 8] = 1;                       // the dark module, again
}

function placeVersion(modules, n, version) {
  if (version < 7) return;
  const bits = versionBits(version);
  for (let i = 0; i < 18; i++) {
    const v = ((bits >>> i) & 1) === 1 ? 1 : 0;
    const r = Math.floor(i / 3);
    const c = n - 11 + (i % 3);
    modules[r * n + c] = v;
    modules[c * n + r] = v;
  }
}

/** The eight standard masks, by number. */
const MASKS = [
  (r, c) => (r + c) % 2 === 0,
  (r) => r % 2 === 0,
  (r, c) => c % 3 === 0,
  (r, c) => (r + c) % 3 === 0,
  (r, c) => (Math.floor(r / 2) + Math.floor(c / 3)) % 2 === 0,
  (r, c) => ((r * c) % 2) + ((r * c) % 3) === 0,
  (r, c) => (((r * c) % 2) + ((r * c) % 3)) % 2 === 0,
  (r, c) => (((r + c) % 2) + ((r * c) % 3)) % 2 === 0,
];

/**
 * The standard's penalty score for one masked matrix. Lower is better; the
 * encoder tries all eight masks and keeps the cheapest, which is what stops a
 * code coming out with a big blank region a scanner cannot lock onto.
 */
function penalty(modules, n) {
  const get = (r, c) => modules[r * n + c] === 1;
  let score = 0;

  // Rule 1: runs of five or more of the same colour, in both directions.
  for (let i = 0; i < n; i++) {
    for (const row of [true, false]) {
      let run = 1;
      let prev = row ? get(i, 0) : get(0, i);
      for (let j = 1; j < n; j++) {
        const cur = row ? get(i, j) : get(j, i);
        if (cur === prev) { run++; continue; }
        if (run >= 5) score += run - 2;
        run = 1;
        prev = cur;
      }
      if (run >= 5) score += run - 2;
    }
  }

  // Rule 2: every 2×2 block of one colour.
  for (let r = 0; r < n - 1; r++) {
    for (let c = 0; c < n - 1; c++) {
      const v = get(r, c);
      if (v === get(r, c + 1) && v === get(r + 1, c) && v === get(r + 1, c + 1)) score += 3;
    }
  }

  // Rule 3: the finder-like 1:1:3:1:1 sequence with four light modules beside it.
  const P1 = [true, false, true, true, true, false, true, false, false, false, false];
  const P2 = [false, false, false, false, true, false, true, true, true, false, true];
  const runs = (r, c, dr, dc, pat) => {
    for (let i = 0; i < 11; i++) {
      const rr = r + dr * i, cc = c + dc * i;
      if (rr >= n || cc >= n || get(rr, cc) !== pat[i]) return false;
    }
    return true;
  };
  for (let r = 0; r < n; r++) {
    for (let c = 0; c < n; c++) {
      if (runs(r, c, 0, 1, P1) || runs(r, c, 0, 1, P2)) score += 40;
      if (runs(r, c, 1, 0, P1) || runs(r, c, 1, 0, P2)) score += 40;
    }
  }

  // Rule 4: how far the proportion of dark modules strays from half.
  let dark = 0;
  for (let i = 0; i < n * n; i++) if (modules[i] === 1) dark++;
  const pct = (dark * 100) / (n * n);
  score += Math.floor(Math.abs(pct - 50) / 5) * 10;
  return score;
}

/* ── Encoding ─────────────────────────────────────────────────────────── */

/** The bit stream for one payload: mode, length, data, terminator, padding. */
function bitStream(bytes, version) {
  const { dataTotal } = capacityOf(version);
  const bits = [];
  const push = (value, len) => {
    for (let i = len - 1; i >= 0; i--) bits.push((value >>> i) & 1);
  };

  push(0b0100, 4);                                    // byte mode
  push(bytes.length, version >= 10 ? 16 : 8);         // character count
  for (const b of bytes) push(b, 8);

  const capacityBits = dataTotal * 8;
  push(0, Math.min(4, capacityBits - bits.length));   // terminator
  while (bits.length % 8) bits.push(0);               // pad to a byte boundary

  const data = new Uint8Array(dataTotal);
  for (let i = 0; i < bits.length; i += 8) {
    let byte = 0;
    for (let j = 0; j < 8; j++) byte = (byte << 1) | bits[i + j];
    data[i / 8] = byte;
  }
  // The standard's alternating pad bytes fill whatever is left.
  for (let i = bits.length / 8, alt = 0; i < dataTotal; i++, alt ^= 1) {
    data[i] = alt ? 0x11 : 0xec;
  }
  return data;
}

/** Splits into blocks, adds Reed-Solomon, and interleaves the lot. */
function interleave(data, version) {
  const { ecPer, g1, g2, blocks, short } = capacityOf(version);
  const dataBlocks = [];
  const ecBlocks = [];
  let offset = 0;
  for (let b = 0; b < blocks; b++) {
    const len = b < g1 ? short : short + 1;
    const block = data.subarray(offset, offset + len);
    offset += len;
    dataBlocks.push(block);
    ecBlocks.push(rsEncode(block, ecPer));
  }

  const out = [];
  const longest = short + (g2 > 0 ? 1 : 0);
  for (let i = 0; i < longest; i++) {
    for (const block of dataBlocks) if (i < block.length) out.push(block[i]);
  }
  for (let i = 0; i < ecPer; i++) {
    for (const block of ecBlocks) out.push(block[i]);
  }
  return Uint8Array.from(out);
}

/** Walks the zig-zag placement path, writing one bit per free module. */
function placeData(modules, reserved, n, codewords) {
  let bit = 0;
  const total = codewords.length * 8;
  let upward = true;
  for (let right = n - 1; right >= 1; right -= 2) {
    if (right === 6) right = 5;                       // column 6 is timing
    for (let step = 0; step < n; step++) {
      const row = upward ? n - 1 - step : step;
      for (const col of [right, right - 1]) {
        if (reserved[row * n + col]) continue;
        let value = 0;
        if (bit < total) {
          value = (codewords[bit >>> 3] >>> (7 - (bit & 7))) & 1;
          bit++;
        }
        modules[row * n + col] = value;
      }
    }
    upward = !upward;
  }
}

/**
 * Encodes `text` and returns the finished module grid.
 *
 * @param {string} text
 * @returns {{size: number, modules: Int8Array}} `modules[r * size + c]` is 1
 *   for a dark module.
 */
export function encodeQr(text) {
  const bytes = new TextEncoder().encode(String(text));
  const version = VERSIONS.findIndex((v, i) => i >= 1 && bytes.length + 2
    <= capacityOf(i).dataTotal - (i >= 10 ? 1 : 0));
  if (version < 1) throw new Error('too much data for a version-10 QR code');

  const n = sizeFor(version);
  const codewords = interleave(bitStream(bytes, version), version);

  // All eight masks, cheapest kept. The penalty rules exist to stop a code
  // coming out with a region a scanner mistakes for a finder pattern.
  let best = null;
  for (let mask = 0; mask < 8; mask++) {
    const { modules, reserved } = skeleton(version);
    placeData(modules, reserved, n, codewords);
    for (let r = 0; r < n; r++) {
      for (let c = 0; c < n; c++) {
        if (reserved[r * n + c]) continue;
        if (MASKS[mask](r, c)) modules[r * n + c] ^= 1;
      }
    }
    placeFormat(modules, n, mask);
    placeVersion(modules, n, version);
    const score = penalty(modules, n);
    if (!best || score < best.score) best = { score, modules };
  }
  return { size: n, modules: best.modules, version };
}

/**
 * The same thing as an `<svg>` string.
 *
 * One `<path>` for every dark module rather than one `<rect>` each: a version-6
 * code is over a thousand modules, and a thousand elements is a thousand things
 * for the browser to lay out. The quiet zone is four modules, as the standard
 * requires — a code drawn hard against its container does not scan.
 */
export function qrSvg(text, { quiet = 4, dark = '#0c0f14', light = '#ffffff' } = {}) {
  const { size, modules } = encodeQr(text);
  const total = size + quiet * 2;
  let d = '';
  for (let r = 0; r < size; r++) {
    for (let c = 0; c < size; c++) {
      if (modules[r * size + c] === 1) d += `M${c + quiet} ${r + quiet}h1v1h-1z`;
    }
  }
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${total} ${total}" `
    + `shape-rendering="crispEdges" role="img" aria-label="QR code">`
    + `<rect width="${total}" height="${total}" fill="${light}"/>`
    + `<path d="${d}" fill="${dark}"/></svg>`;
}

export default { encodeQr, qrSvg };
